# This file allows you to configure Airflow Connections, Pools, and Variables in a single place for local development only.
# NOTE: json dicts can be added to the conn_extra field as yaml key value pairs. See the example below.

# For more information, refer to our docs: https://www.astronomer.io/docs/astro/cli/develop-project#configure-airflow_settingsyaml-local-development-only
# For questions, reach out to: https://support.astronomer.io
# For issues create an issue ticket here: https://github.com/astronomer/astro-cli/issues

airflow:
  connections:
    - conn_id: "http:infrabel"
      conn_type: "http"
      conn_host: "opendata.infrabel.be"
      conn_schema: "https"
    - conn_id: "duckdb:memory"
      conn_type: "duckdb"
      conn_host: ":memory:"
    - conn_id: "postgres:datawarehouse"
      conn_type: "postgres"
      conn_host: "datawarehouse" # docker network ls -> edit docker-compose.yaml -> docker compose up (help: docker network <network> <container>)
      conn_schema: "postgres"
      conn_login: "postgres"
      conn_password: "postgres"
      conn_port: "5432"
#    - conn_id:
#      conn_type:
#      conn_host:
#      conn_schema:
#      conn_login:
#      conn_password:
#      conn_port:
#      conn_extra:
#        example_extra_field: example-value
  pools:
    - pool_name:
      pool_slot:
      pool_description:
  variables:
    - variable_name:
      variable_value:
