version: "3.1"

services:
  data-warehouse:
    image: postgres:16
    container_name: datawarehouse
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - data-warehouse:/var/lib/postgresql/data
    restart: always
    ports:
      - "5433:5432"
    networks:
      - astro-cli

volumes:
  data-warehouse:

networks:
  astro-cli:
    name: airflow_b21f3b_airflow
    external: true